<a href="https://colab.research.google.com/github/taiebat/NumPy/blob/master/NumPy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**bold text**# NumPy Exercise

## Morteza Taiebat
#### University of Michigan

## NumPy
- is a Python package developed for scientific computing,
- is built largely around an n-dimensional array (ndarray) object
- includes various other capabilities, including linear algebra and random number generation. (see numpy.org)

To get started, import the NumPy package.

In [1]:
import numpy as np

## Data types

- NumPy has multiple data types.
- In some cases, the number of bits (e.g. 16, 32, 64) can be specified.
- An underscore represents the default size.
For example:

In [3]:
np.int64(4.7)

4

In [4]:
np.float64(4.3)

4.3

In [5]:
np.bool_(1)

True

## Array creation

Create ndarray of zeros. Input is a tuple defining the shape.

In [7]:
np.zeros((3,2)).shape

(3, 2)

Create ndarray from Python lists. You can specify the number type (default is `np.float64`).

In [8]:
np.array([[1.,2.,3.],[4.,5.,6.]],dtype=np.int_)

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
np.array([[1.,2.,3.],[4.,5.,6.]],dtype=np.float_)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [10]:
np.array([[[1.,2.],[3.,4.]],[[5.,6.],[7.,8.]]],dtype=np.float_)

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

Use the `np.arange` function to create a ndarray with a given start, end, and stride:

In [11]:
np.arange(1.2,6,.5)

array([1.2, 1.7, 2.2, 2.7, 3.2, 3.7, 4.2, 4.7, 5.2, 5.7])

Create a ndarray of random numbers. We'll look more at NumPy's random number capabilities later.

In [12]:
np.random.rand(2,2)

array([[0.08894065, 0.64078885],
       [0.55248372, 0.51608481]])

### Exercise

Create a 1D array starting at 10 and going backwards by 0.5 until 2.5 (inclusive).

In [15]:
np.arange(10,2,-0.5)

array([10. ,  9.5,  9. ,  8.5,  8. ,  7.5,  7. ,  6.5,  6. ,  5.5,  5. ,
        4.5,  4. ,  3.5,  3. ,  2.5])

## Input/Output

Save a ndarray to a file:

In [20]:
a = np.random.rand(4,4)
print(a)
np.savetxt('out.txt',a, fmt='%.4e',delimiter='\t',header='4 x 4 random array')

[[0.48254053 0.3155437  0.23285644 0.97547767]
 [0.09972749 0.83906524 0.00683146 0.03482877]
 [0.40395131 0.83006248 0.64659471 0.53229006]
 [0.82668431 0.48525326 0.1659045  0.76600402]]


Load the file to a ndarray:

In [21]:
np.loadtxt('out.txt')

array([[0.4825405 , 0.3155437 , 0.2328564 , 0.9754777 ],
       [0.09972749, 0.8390652 , 0.00683146, 0.03482877],
       [0.4039513 , 0.8300625 , 0.6465947 , 0.5322901 ],
       [0.8266843 , 0.4852533 , 0.1659045 , 0.766004  ]])

### Exercise

Create a 2 x 3 array of ones. Save it to a file named 'ones.txt', with integer format and separated by single spaces.

In [22]:
a = np.ones((2,3))
print(a)
np.savetxt('ones.txt',a, fmt='%d',delimiter=' ')

[[1. 1. 1.]
 [1. 1. 1.]]


In [23]:
np.loadtxt('ones.txt')

array([[1., 1., 1.],
       [1., 1., 1.]])

## Indexing/Slicing

One nice feature of NumPy arrays is the versatility in accessing their components.

### Indexing

In [24]:
b = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


Array elements and subdimensional arrays can be accessed with square brackets:

In [25]:
b[0]

array([1., 2., 3.])

In [26]:
b[0][1]

2.0

It's actually more efficient to use the following syntax for multiple indices:

In [27]:
b[0,1]

2.0

In [28]:
print(b)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


Lists of indices can also be used:

In [29]:
b[0,[0,2]]

array([1., 3.])

In [30]:
b[[0,2],[0,1]]

array([1., 8.])

A list or array of booleans can also be used:

In [31]:
c = np.arange(0,.6,.1)
print(c)

[0.  0.1 0.2 0.3 0.4 0.5]


In [32]:
c[[True,False,False,True,False,True]]

array([0. , 0.3, 0.5])

### Slicing

In [47]:
print(b)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


The colon (:) is used to specify slicing and striding.

Initial and final indices can be given (the final index is not inclusive).

In [51]:
b[1:3,0:2]

array([[4., 5.],
       [7., 8.]])

In [42]:
print(b)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


The initial index can be dropped to start at the beginning.
The final index can be dropped to go to the end.

In [52]:
b[1:,:2]

array([[4., 5.],
       [7., 8.]])

If both indices are dropped, all elements along that axis are taken:

In [55]:
b[:,0]

array([1., 4., 7.])

A second colon can be used to define a stride:

In [56]:
c = np.arange(0,1,.1)
print(c)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [57]:
c[1:9:2]

array([0.1, 0.3, 0.5, 0.7])

### Exercise

**Create** a 5 x 5 array of zeros. Replace the 2nd and 4th rows and columns with 1's.

In [58]:
a = np.zeros((5,5))
print(a)
a[[1,3],:] = 1
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]]


## Copies and views

When assigning data to a ndarray from a previous ndarray, three things can happen:
- No copy is made
- A shallow copy (a "view") is made
- A deep copy is made

- A simple assignment from one ndarray to another results in no copy being made.
- The original ndarray is simple given an additional name.

In [59]:
a = np.random.rand(2,4)
b = a
a is b

True

- Changes can be made using either name:

In [ ]:
print(a)

In [60]:
b[0,0] = 0.
print(a)

[[0.         0.91558204 0.25608989 0.3691255 ]
 [0.56574134 0.81492356 0.19977502 0.71934695]]


- A shallow copy or "view" creates a new ndarray.
- Data is still shared with the original array.
- A view can be explicity created using the `view()` method.

In [68]:
c = a.view()
c is a

False

In [69]:
c.base is a

True

In [70]:
print(a)

[[0.         0.91558204 0.25608989 0.3691255 ]
 [0.56574134 0.81492356 0.19977502 0.71934695]]


In [66]:
c[0,1] = 1.
print(a)

[[0.         0.91558204 0.25608989 0.3691255 ]
 [0.56574134 0.81492356 0.19977502 0.71934695]]


Simple slicing also returns a view:

In [71]:
d = a[:,1]
print(d)
print(a)

[0.91558204 0.81492356]
[[0.         0.91558204 0.25608989 0.3691255 ]
 [0.56574134 0.81492356 0.19977502 0.71934695]]


In [ ]:
d[1] = 2.
print(d)
print(a)
d.base is a

- A deep copy creates a new ndarray.
- Data is NOT shared with the original ndarray.
- A deep copy can be forced by using the `copy` method:

In [72]:
e = a.copy()
e.base is a

False

In [73]:
e.base is a

False

In [74]:
print(a)

[[0.         0.91558204 0.25608989 0.3691255 ]
 [0.56574134 0.81492356 0.19977502 0.71934695]]


In [75]:
e[0,0] = 1.5
print(e)

[[1.5        0.91558204 0.25608989 0.3691255 ]
 [0.56574134 0.81492356 0.19977502 0.71934695]]


In [76]:
print(a)

[[0.         0.91558204 0.25608989 0.3691255 ]
 [0.56574134 0.81492356 0.19977502 0.71934695]]


- "Complicated" indexing returns a deep copy, not a view:

In [77]:
f = a[1,[0,2,3]]
f.base is a

False

## Exercise
- Some methods of indexing return a view and others return a deep copy. Check the following indexing methods to see which returns what:

In [82]:
g = a[1:,:]
g.base is a

True

In [80]:
g = a[0,[0,1,2,3]]
g.base is a

False

In [83]:
g = a[0,2]
g.base is a

False

## Combining arrays

NumPy has multiple functions that combine a sequence of ndarrays into a single ndarray.

### `np.concatenate`


`np.concatenate` combines ndarrays while maintaining the dimensionality of the original ndarrays
- e.g. 2D arrays combine to form a larger 2D array

In [91]:
a = np.random.rand(2,2)
b = np.random.rand(2,2)
np.concatenate((a,b))

array([[0.60024463, 0.95469355],
       [0.04421584, 0.40010011],
       [0.76530097, 0.54429338],
       [0.50911176, 0.02005925]])

Arrays must have the same size, except in the dimension along which they are being combined.
- e.g., two arrays with sizes (3,4,4) and (2,4,4) can be concatenated along the 0-axis, but not the 1-axis or 2-axis.

The axis argument is used to define the axis along which the arrays will be concatenated.
- e.g., `axis=0` combines the two arrays as concatenated rows, with a final size of (4,2).
- This is the default behavior.

In [94]:
np.concatenate((a,b),axis=0)

array([[0.60024463, 0.95469355],
       [0.04421584, 0.40010011],
       [0.76530097, 0.54429338],
       [0.50911176, 0.02005925]])

Using `axis=1` combines the arrays as concatenated columns, with a final size of (2,4).

In [95]:
np.concatenate((a,b),axis=1)

array([[0.60024463, 0.95469355, 0.76530097, 0.54429338],
       [0.04421584, 0.40010011, 0.50911176, 0.02005925]])

### `np.vstack` and `np.hstack`

The `np.vstack` function ("vertical stack") is a shortcut for `np.concatenate` with `axis=0`:

In [96]:
np.vstack((a,b))

array([[0.60024463, 0.95469355],
       [0.04421584, 0.40010011],
       [0.76530097, 0.54429338],
       [0.50911176, 0.02005925]])

The `np.hstack` function ("horizontal stack") is a shortcut for `np.concatenate` with `axis=1`:

In [97]:
np.hstack((a,b))

array([[0.60024463, 0.95469355, 0.76530097, 0.54429338],
       [0.04421584, 0.40010011, 0.50911176, 0.02005925]])

### `np.stack`

- The function `np.stack` combines a sequence of arrays while increasing the dimensionality by one.
- The arrays being combined must all have the same size.

In [98]:
np.stack((a,b))

array([[[0.60024463, 0.95469355],
        [0.04421584, 0.40010011]],

       [[0.76530097, 0.54429338],
        [0.50911176, 0.02005925]]])

### Exercise

Combine the following 2D array of x data with the 1D array of y data into a single 10x3 array. (This might be done, for example, if you were going to save the data in a single file.)

In [101]:
x = np.random.rand(10,2)
y = np.random.rand(10,1)

np.hstack((x,y)).shape
np.concatenate((x,y), axis = 1).shape

(10, 3)

## Manipulating array shape

The dimensions of a ndarray are called it's "shape."

In [102]:
a = np.random.rand(3,2)
print(a)

[[0.69628003 0.73502359]
 [0.74194335 0.12427013]
 [0.26379154 0.82362577]]


In [103]:
a.shape

(3, 2)

The ndarray can be flattened into a 1D array (the default is to go row-by-row):

In [104]:
a.flatten()

array([0.69628003, 0.73502359, 0.74194335, 0.12427013, 0.26379154,
       0.82362577])

In [108]:
a.ravel() 

array([0.69628003, 0.73502359, 0.74194335, 0.12427013, 0.26379154,
       0.82362577])

In [111]:
a.flatten().base is a
a.ravel().base is a

True

`flatten()` always returns a deep copy, whereas `ravel()` will return a view, if possible.

The dimensions can be modified more generally, as long as the total number of elements remains the same (using -1 tells reshape to figure out what the number should be):

In [112]:
a.reshape(2,3)

array([[0.69628003, 0.73502359, 0.74194335],
       [0.12427013, 0.26379154, 0.82362577]])

In [113]:
a.reshape(2,1,-1)

array([[[0.69628003, 0.73502359, 0.74194335]],

       [[0.12427013, 0.26379154, 0.82362577]]])

In [114]:
print(a)

[[0.69628003 0.73502359]
 [0.74194335 0.12427013]
 [0.26379154 0.82362577]]


Note that `reshape` is returning a view. To actually modify the ndarray, use `resize`:

In [115]:
a.resize(2,1,3)
print(a)

[[[0.69628003 0.73502359 0.74194335]]

 [[0.12427013 0.26379154 0.82362577]]]


### Exercise

The following array provides [x,y,z] data on a grid (used, for example, for a surface plot). Reshape the array into an Nx3 array (e.g. for output to a file, or for a scatter plot).

In [119]:
x,y = np.meshgrid([0.,.5,1.],[0.,.5,1.])
z = x**2 + y**2
data = np.stack((x,y,z)).T

data.shape
data.reshape(-1,3)

array([[0.  , 0.  , 0.  ],
       [0.  , 0.5 , 0.25],
       [0.  , 1.  , 1.  ],
       [0.5 , 0.  , 0.25],
       [0.5 , 0.5 , 0.5 ],
       [0.5 , 1.  , 1.25],
       [1.  , 0.  , 1.  ],
       [1.  , 0.5 , 1.25],
       [1.  , 1.  , 2.  ]])

## Arithmetic operators

Basis arithmetic operators act elementwise between two arrays of the same shape:

In [120]:
a = np.zeros((2,1))
b = np.ones((2,1))
a+b

array([[1.],
       [1.]])

In [122]:
b/a

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf],
       [inf]])

In [124]:
np.inf * 0

nan

## Broadcasting
- Operations can take place between arrays of different shape in certain conditions.
- This is called "broadcasting".
- Starting from the trailing dimensions, either:
    - the two dimensions must be equal, or
    - one dimesion must be 1.

In [125]:
a = np.array([[1.,2.],[3.,4.]])
b = np.array([[1.],[2.]])
print(a,b)
print(a.shape,b.shape)
a*b

[[1. 2.]
 [3. 4.]] [[1.]
 [2.]]
(2, 2) (2, 1)


array([[1., 2.],
       [6., 8.]])

Other examples that work:

In [128]:
a = 5.
b = np.ones((2,3))
c = a*b
c

array([[5., 5., 5.],
       [5., 5., 5.]])

In [129]:
a = np.random.rand(1,3,2,1,5)
b = np.random.rand(    2,4,5)
c = a+b
c

array([[[[[0.75376421, 1.27967159, 1.14934631, 0.47468015, 0.82173446],
          [1.32280301, 1.33454621, 0.8956608 , 0.23636347, 0.5686095 ],
          [1.33932579, 0.95771191, 0.4968298 , 0.24201555, 0.59847303],
          [1.50570413, 0.74135998, 0.55437072, 0.58706192, 0.39671106]],

         [[1.23348768, 1.7788648 , 0.53900529, 0.87646586, 0.96017398],
          [0.9822117 , 0.99791369, 0.51778919, 0.53984972, 1.43961994],
          [0.98020932, 1.16317047, 0.42666301, 0.89470789, 1.83960794],
          [0.93722835, 1.74250083, 0.61182605, 0.70217087, 1.43683222]]],


        [[[0.98342053, 1.07245232, 1.44498741, 1.10087029, 0.7059361 ],
          [1.55245933, 1.12732694, 1.1913019 , 0.86255362, 0.45281115],
          [1.56898211, 0.75049264, 0.7924709 , 0.86820569, 0.48267467],
          [1.73536046, 0.53414071, 0.85001182, 1.21325206, 0.2809127 ]],

         [[1.28149426, 1.73116701, 1.06503888, 0.91512954, 0.26140292],
          [1.03021828, 0.9502159 , 1.04382278, 0.5785134

Examples that don't work:

In [132]:
a = np.ones((2,2))
b = np.ones((3,2))
#c = a+b

In [ ]:
a = np.random.rand(1,3,2,2,5)
b = np.random.rand(    2,4,5)
#c = a+b

### Exercise
Which of the following pairs of arrays can be broadcast together?

In [138]:
a = np.random.rand(3,4,2,4)
b = np.random.rand(      1)
a+b

array([[[[0.94200966, 1.42253858, 0.94909125, 1.10912029],
         [1.17596686, 0.9880075 , 0.92280447, 1.2156548 ]],

        [[1.38411708, 1.53594182, 0.63731403, 1.40090756],
         [0.85732921, 0.8010165 , 1.17192743, 1.06457426]],

        [[1.48089595, 0.71971936, 0.89836348, 1.37935878],
         [1.09894182, 1.04930262, 1.06245179, 0.9144812 ]],

        [[1.00101423, 1.55938209, 0.88575117, 0.66378924],
         [1.104787  , 1.00881408, 1.04071265, 1.20224235]]],


       [[[0.76884091, 1.40058259, 1.30364106, 0.59841901],
         [0.58986431, 1.32938611, 0.56768267, 1.22867412]],

        [[1.36819479, 0.65787509, 1.40609892, 0.74088245],
         [0.86828972, 1.35034688, 0.57973883, 0.9519194 ]],

        [[1.00663127, 1.21701836, 0.5666295 , 1.0006431 ],
         [1.22690283, 1.20883195, 1.03209245, 1.03445283]],

        [[1.38197019, 0.6179653 , 1.44115867, 1.43456941],
         [0.66877293, 0.72368249, 1.10542474, 1.11898114]]],


       [[[0.93789793, 1.26098565, 1.

In [139]:
a = np.random.rand(3,3,2,1)
b = np.random.rand(1,2,1,1)
a+b

ValueError: ignored

In [ ]:
a = np.random.rand(3,1,2,1)
b = np.random.rand( 2,2,11)
a+b

In [ ]:
a = np.random.rand(  3,4)
b = np.random.rand(3,4,2)
a + b

## Linear algebra

2D NumPy arrays can be treated as matrices for basic linear algebra operations:

In [140]:
a = np.array([[1.,2.],[3.,4.]])
print(a)

[[1. 2.]
 [3. 4.]]


Transpose:

In [141]:
a.T

array([[1., 3.],
       [2., 4.]])

In [142]:
a.transpose()

array([[1., 3.],
       [2., 4.]])

Inverse:

In [143]:
inva = np.linalg.inv(a)
print(inva)

[[-2.   1. ]
 [ 1.5 -0.5]]


Matrix multiplication:
- Remember the * operator for elementwise multiplication
- The @ operator does matrix multiplication in Python 3

In [144]:
inva.dot(a)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [145]:
inva @ a

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

Matrix/vector solve:

In [146]:
b = np.array([[3],[7]])
np.linalg.solve(a,b) #np.inv(a)*b

array([[1.],
       [1.]])

Eigenvalues/eigenvectors (returns a tuple containg a vector of the eigenvalues and a matrix whose columns are the eigenvectors):

In [147]:
np.linalg.eig(a)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

Identity matrix:

In [148]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

### Exercise

Verify that `np.linalg.solve` is giving correct results. I.e. given $x = A^{-1}b$, verify that $Ax = b$.

In [155]:
A = np.array([[2.,6.],[0.,1.]])
b = np.array([[1.],[0.]])

x = np.linalg.solve(A, b)
A @ x

array([[1.],
       [0.]])

Verify that `np.linalg.eig` is giving correct results. I.e. using the eigenvalues $\lambda_i$ and eigenvectors $\boldsymbol{\xi}_i$ from the matrix $A$, verify that $A\boldsymbol{\xi}_i = \lambda_i\boldsymbol{\xi}_i$.

In [156]:
A = np.array([[2.,6.],[0.,1.]])
val, vec = np.linalg.eig(A)
print(val,vec)

A @ vec[:,0] == val[0]*vec[:,0]

[2. 1.] [[ 1.         -0.98639392]
 [ 0.          0.16439899]]


array([ True,  True])

## Random sampling

NumPy has several functions for random sampling.

Uniformly sampled from $[0,1)$ for a given shape:

In [157]:
  np.random.rand(2,3)

array([[0.77363789, 0.24970458, 0.1962771 ],
       [0.07444255, 0.71911394, 0.56059312]])

Random sample from standard normal distribution (0 mean, 1 std. dev.):

In [158]:
np.random.randn(1,2)

array([[-0.28922453,  2.10644766]])

Random integers, specifying lower (inclusive) and upper (exclusive) bounds:

In [159]:
np.random.randint(1,11,(1,3))

array([[5, 6, 2]])

Shuffle contents of array:
- Only along first axis - e.g. shuffling a matrix maintains rows
- `shuffle` modifies the original array
- `permutation` returns a new, shuffled array

In [160]:
a = np.arange(0,12).reshape(3,-1)
np.random.permutation(a)

array([[ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [164]:
b = np.array([[1.,2.],[3.,4.],[5.,6.]])
np.random.shuffle(b)
print(b)

[[1. 2.]
 [5. 6.]
 [3. 4.]]


### Exercise

Draw four random numbers (*with no repeats*) from the set of integers 1 through 10.

In [176]:
np.random.permutation(np.arange(1,11))[:4]

array([7, 9, 2, 4])

## Other useful functions and methods

### Sorting

NumPy's `sort` function will sort elements, from low to high:
- Note that rows, columns, etc. are not maintained 
- The axis can be specifed (the default is to sort along the last axis)

In [177]:
a = np.array([[1.,5.],[3.,1.],[2,0.]])
print(a)

[[1. 5.]
 [3. 1.]
 [2. 0.]]


In [181]:
np.sort(a)

array([[1., 5.],
       [1., 3.],
       [0., 2.]])

In [182]:
np.sort(a,axis=0)

array([[1., 0.],
       [2., 1.],
       [3., 5.]])

This is also available as a method that modifies the array:

In [183]:
a.sort()
print(a)

[[1. 5.]
 [1. 3.]
 [0. 2.]]


The indices of the sorted elements are given using `argsort`:
- This is useful if you want to, for example, sort an array by the first column and maintain rows

In [184]:
ind = np.argsort(a,axis=0)
print(ind)

[[2 2]
 [0 1]
 [1 0]]


### Exercise

Use `argsort` to sort the following matrix by the first column, while keeping the contents of each row unchanged:

In [188]:
a = np.array([[3.,1.],[0.,4.],[1.,8.]])
print(a)

a[ind[:,0]]


[[3. 1.]
 [0. 4.]
 [1. 8.]]


array([[0., 4.],
       [3., 1.],
       [3., 1.]])

The correct answer should give:

In [ ]:
a = np.array([[0.,4.],[1.,8.],[3.,1.]])
print(a)

### Reduction/summarization functions

NumPy has several functions that "reduce" an array to a single value or smaller set of values, such as `min`, `max`, `sum`, and `prod`:

In [189]:
a = np.random.randint(2,11,5)
print(a)

[10  5  4  9  8]


In [190]:
np.min(a)

4

In [191]:
np.max(a)

10

In [192]:
np.sum(a)

36

In [193]:
np.prod(a)

14400

### Exercise

Compute the average of `a` (without using `np.average` or `np.mean`).

In [195]:
np.sum(a)/np.size(a)

5

### "Universal" functions

NumPy has several standard mathematical functions that apply elementwise to ndarrays, e.g:

In [196]:
a = np.random.rand(2,2)

In [197]:
np.exp(a)

array([[1.09440116, 2.60921505],
       [1.2466519 , 1.09658436]])

In [198]:
np.sqrt(a)

array([[0.30034534, 0.97931069],
       [0.46953325, 0.30364489]])

In [199]:
np.sin(a)

array([[0.09008503, 0.81864603],
       [0.21867995, 0.09206964]])

In [200]:
np.arctan(a)

array([[0.08996383, 0.76449792],
       [0.21699043, 0.09194028]])